language: node_js
node_js:
- '0.10'
before_install: npm install -g mocha
deploy:
  provider: s3
  access_key_id: AKIAJXLOWRXANL7GUNBA
  secret_access_key:
    secure: xb3MMiRUI13I7CUKOs0hS6RthmKCv3EbwXZr056TJIdH2kD2xFxntSNAYupMvAse0PLh3CDkTJ5TaT0hcZf5P8cescDrECBYVDgnAkyeypVZvckq1xwSnDLgCeUOQSrB/3p8YrxMlFutedN6hx55/AWmnqQ/DX21MuItUDF5ByKP1Q8slzlrbDawlSK8hF5ggdl2JrtlH6vC5Jf7nJUn1ofwGkZIeUvbJTj7HAWyWCHZJCjugoQKCXTb02ihQP8uXabJ2J6ZxfEduSu6FUe5h2vPd6igu8Q0TVZ+RLyvC/CF9n03h5oK8Fp/XhlaQwNEB59628nV3f2uuwyFp3OeTwNEq9fc5CmeToxIt/OySValh+xxPHiuN+3owlFA7kbSqBNzJg4LI99S1meFo2RhYXFyFO4WH+jgbP/Na8lySIRvI2n5i2+O+c3fnhqzkY/9sZb/s4NtK5I1MW27WdO3M9gjokMhsUTF2HK/TFHSy3hUm7hFdSsrrKTTn/2dCmShipL5z0d2lXftd4ji8vjDGu7OiqX1Yk2k+iK1C41ZvrsgjejeFyOd95Q0P4l0lpbnbEIVAcszc2RNWD7+qnKAdexcq/Fp4O/hY08r+FBB0FJKzR4X3NNtCn74Wq5l5QnRJVmJj8EN3VlXUxjhyPdZgOSQDfXbRloZ9nrytVLXK+E=
  bucket: deploy-weeia
  upload-dir: dyjas
  acl: public_read
  on:
    repo: cidan333/ciTestDyjas
